name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft-d365-ce-pfe-devops/D365-CE-Pipelines
      endpoint: tyler-hogsett-microsoft

jobs:
- template: jobs/pack-import-solution.yml@templates